name: Deploy Contracts to NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: '5.0'
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}

    - name: Build Project
      run: |
        dotnet build BattleNotifications.Contracts --configuration Release

    - name: Build solution and generate NuGet package
      run: |  
        cd BattleNotifications.Contracts
        dotnet pack -c Release -o out  

    - name: Push generated package to NuGet registry
      run: dotnet nuget push ./BattleNotifications.Contracts/out/*.nupkg -k ${{secrets.NUGET_TOKEN}} --skip-duplicate --no-symbols true
    